<?php
/**
 * 编辑卖家产品和标准---------------ISL231106
 */
$remote['seller_edit_seller_product1'] = array(
    'url' => '/sl/slInfo/slQlt/newOrUpdate',

    'request' => array(
        'member_id' => array(
            'name' => '登陆的用户ID',
            'column' => 'loginId',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'param' => array(
            'name' => '参数',
            'column' => 'param',
            'type' => 'object',
            'default' => Array(),
        ),
    ),

    'param' => array(

        'slPdMctList' => array(
            'name' => '卖家产品加工技术标准信息List',
            'column' => 'slPdMctList',
            'type' => 'List',
            'default' => '',
            'require' => false,
        ),
        'slPdTncList' => array(
            'name' => '卖家产品加工质量标准指标',
            'column' => 'slPdTncList',
            'type' => 'List',
            'default' => '',
            'require' => false,
        ),
        'slPdPkgList' => array(
            'name' => '卖家产品包装标准信息',
            'column' => 'slPdPkgList',
            'type' => 'List',
            'default' => '',
            'require' => false,
        ),
        'slPdOrgStdList' => array(
            'name' => '卖家原种种源标准',
            'column' => 'slPdOrgStdList',
            'type' => 'List',
            'default' => '',
            'require' => false,
        ),
        'slPdFedStdList' => array(
            'name' => '卖家产品饲养标准',
            'column' => 'slPdFedStdList',
            'type' => 'List',
            'default' => '',
            'require' => false,
        ),
        'slPdGnqStdList' => array(
            'name' => '卖家产品通用质量标准',
            'column' => 'slPdGnqStdList',
            'type' => 'List',
            'default' => '',
            'require' => false,
        ),
        'slPdTspStdList' => array(
            'name' => '卖家产品储存运输标准',
            'column' => 'slPdTspStdList',
            'type' => 'List',
            'default' => '',
            'require' => false,
        ),
        'slPdSftStdList' => array(
            'name' => '卖家产品安全标准',
            'column' => 'slPdSftStdList',
            'type' => 'List',
            'default' => '',
            'require' => false,
        ),
    ),


    'slPdMctList' => array(
        'slPdMctList    ' => array(
            'name' => '卖家产品加工技术标准信息List',
            'column' => 'slPdMctList    ',
            'type' => 'List',
            'default' => '',
            'require' => false,
        ),
        'slCode' => array(
            'name' => '卖家编码',
            'column' => 'slCode',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'slPdId' => array(
            'name' => '卖家产品ID',
            'column' => 'slPdId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'slQltStd' => array(
            'name' => '卖家产品加工技术标准指标',
            'column' => 'slQltStd',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'slQltGradeCode' => array(
            'name' => '产品加工技术标准定级',
            'column' => 'slQltGradeCode',
            'type' => 'Integer',
            'default' => '优良，合格,不合格,论证中（有不同意），禁止准入（有不同意）',
            'require' => false,
        ),
        'loginId' => array(
            'name' => '  创建者ID/更新者ID',
            'column' => 'loginId',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'delFlg' => array(
            'name' => '  删除标志',
            'column' => 'delFlg',
            'type' => 'String',
            'default' => '0：有效，1：删除',
            'require' => false,
        ),
        'ver' => array(
            'name' => '版本号',
            'column' => 'ver',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'slPdMctStdList' => array(
            'name' => '卖家产品加工技术标准指标值信息List',
            'column' => 'slPdMctStdList',
            'type' => 'List',
            'default' => '',
            'require' => false,
        ),
    ),
    'slPdMctStdList' => array(
        'slCode' => array(
            'name' => '卖家编码',
            'column' => 'slCode',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'standardId' => array(
            'name' => '产品标准ID',
            'column' => 'standardId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'stdItemId' => array(
            'name' => '质量标准项目ID',
            'column' => 'stdItemId',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'agreeFlg' => array(
            'name' => '卖家同意标志',
            'column' => 'agreeFlg',
            'type' => 'String',
            'default' => '0:否，1:同意',
            'require' => false,
        ),
        'stdVal' => array(
            'name' => '卖家质量标准',
            'column' => 'stdVal',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'loginId' => array(
            'name' => '  创建者ID/更新者ID',
            'column' => 'loginId',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'delFlg' => array(
            'name' => '  删除标志',
            'column' => 'delFlg',
            'type' => 'String',
            'default' => '0：有效，1：删除',
            'require' => false,
        ),
        'ver' => array(
            'name' => '版本号',
            'column' => 'ver',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
    ),

    'slPdTncList' => array(
        'slCode' => array(
            'name' => '卖家编码',
            'column' => 'slCode',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'slPdId' => array(
            'name' => '卖家产品ID',
            'column' => 'slPdId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'slTncStd' => array(
            'name' => '卖家产品技术标准',
            'column' => 'slTncStd',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'slTncGradeCode' => array(
            'name' => '产品技术标准定级',
            'column' => 'slTncGradeCode',
            'type' => 'Integer',
            'default' => 'A1，A2,A3,论证中（有不同意），禁止准入（有不同意）',
            'require' => false,
        ),
        'loginId' => array(
            'name' => '创建者ID/更新者ID',
            'column' => 'loginId',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'delFlg' => array(
            'name' => '删除标志',
            'column' => 'delFlg',
            'type' => 'String',
            'default' => '0：有效，1：删除',
            'require' => false,
        ),
        'ver' => array(
            'name' => '版本号',
            'column' => 'ver',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'slPdTncStdList' => array(
            'name' => '卖家产品加工质量标准指标值',
            'column' => 'slPdTncStdList',
            'type' => 'List',
            'default' => '',
            'require' => false,
        ),
    ),
    'slPdTncStdList' => array(
        'slCode' => array(
            'name' => '卖家编码',
            'column' => 'slCode',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'standardId' => array(
            'name' => '产品标准ID',
            'column' => 'standardId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'stdItemId' => array(
            'name' => '技术标准项目ID',
            'column' => 'stdItemId',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'agreeFlg' => array(
            'name' => '卖家同意标志',
            'column' => 'agreeFlg',
            'type' => 'String',
            'default' => '0:否，1:同意',
            'require' => false,
        ),
        'stdVal' => array(
            'name' => '卖家技术标准',
            'column' => 'stdVal',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'loginId' => array(
            'name' => '  创建者ID/更新者ID',
            'column' => 'loginId',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'delFlg' => array(
            'name' => '  删除标志',
            'column' => 'delFlg',
            'type' => 'String',
            'default' => '0：有效，1：删除',
            'require' => false,
        ),
        'ver' => array(
            'name' => '版本号',
            'column' => 'ver',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
    ),

    'slPdPkgList' => array(
        'slCode' => array(
            'name' => '卖家编码',
            'column' => 'slCode',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'slPdId' => array(
            'name' => '卖家产品ID',
            'column' => 'slPdId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'slPdPkgId' => array(
            'name' => '卖家产品包装ID',
            'column' => 'slPdPkgId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'standardId' => array(
            'name' => '产品标准ID',
            'column' => 'standardId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'pkgCode' => array(
            'name' => '包装编码',
            'column' => 'pkgCode',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
    ),

    'slPdOrgStdList' => array(
        'slCode' => array(
            'name' => '卖家编码',
            'column' => 'slCode',
            'type' => 'String',
            'default' => '可能多重',
            'require' => false,
        ),
        'slPdId' => array(
            'name' => '卖家产品ID',
            'column' => 'slPdId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'standardId' => array(
            'name' => '产品标准ID',
            'column' => 'standardId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'stdItemId' => array(
            'name' => '技术标准项目ID',
            'column' => 'stdItemId',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'agreeFlg' => array(
            'name' => '卖家同意标志',
            'column' => 'agreeFlg',
            'type' => 'String',
            'default' => '0:否，1:优良，2：合格/一般，3不合格/差',
            'require' => false,
        ),
    ),

    'slPdFedStdList' => array(
        'slCode' => array(
            'name' => '卖家编码',
            'column' => 'slCode',
            'type' => 'String',
            'default' => '可能多重',
            'require' => false,
        ),
        'slPdId' => array(
            'name' => '卖家产品ID',
            'column' => 'slPdId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'standardId' => array(
            'name' => '产品标准ID',
            'column' => 'standardId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'stdItemId' => array(
            'name' => '技术标准项目ID',
            'column' => 'stdItemId',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'agreeFlg' => array(
            'name' => '卖家同意标志',
            'column' => 'agreeFlg',
            'type' => 'String',
            'default' => '0:否，1:优良，2：合格/一般，3不合格/差',
            'require' => false,
        ),
    ),

    'slPdGnqStdList' => array(
        'slCode' => array(
            'name' => '卖家编码',
            'column' => 'slCode',
            'type' => 'String',
            'default' => '可能多重',
            'require' => false,
        ),
        'slPdId' => array(
            'name' => '卖家产品ID',
            'column' => 'slPdId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'standardId' => array(
            'name' => '产品标准ID',
            'column' => 'standardId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'stdItemId' => array(
            'name' => '技术标准项目ID',
            'column' => 'stdItemId',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'agreeFlg' => array(
            'name' => '卖家同意标志',
            'column' => 'agreeFlg',
            'type' => 'String',
            'default' => '0:否，1:优良，2：合格/一般，3不合格/差',
            'require' => false,
        ),
    ),

    'slPdTspStdList' => array(
        'slCode' => array(
            'name' => '卖家编码',
            'column' => 'slCode',
            'type' => 'String',
            'default' => '可能多重',
            'require' => false,
        ),
        'slPdId' => array(
            'name' => '卖家产品ID',
            'column' => 'slPdId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'standardId' => array(
            'name' => '产品标准ID',
            'column' => 'standardId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'stdItemId' => array(
            'name' => '技术标准项目ID',
            'column' => 'stdItemId',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'agreeFlg' => array(
            'name' => '卖家同意标志',
            'column' => 'agreeFlg',
            'type' => 'String',
            'default' => '0:否，1:优良，2：合格/一般，3不合格/差',
            'require' => false,
        ),
    ),

    'slPdSftStdList' => array(
        'slCode' => array(
            'name' => '卖家编码',
            'column' => 'slCode',
            'type' => 'String',
            'default' => '可能多重',
            'require' => false,
        ),
        'slPdId' => array(
            'name' => '卖家产品ID',
            'column' => 'slPdId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'standardId' => array(
            'name' => '产品标准ID',
            'column' => 'standardId',
            'type' => 'Integer',
            'default' => '',
            'require' => false,
        ),
        'stdItemId' => array(
            'name' => '技术标准项目ID',
            'column' => 'stdItemId',
            'type' => 'String',
            'default' => '',
            'require' => false,
        ),
        'agreeFlg' => array(
            'name' => '卖家同意标志',
            'column' => 'agreeFlg',
            'type' => 'String',
            'default' => '0:否，1:优良，2：合格/一般，3不合格/差',
            'require' => false,
        ),
    ),

    'response' => array(),

);