<?php

// +----------------------------------------------------------------------
// | VMCSHOP [V M-Commerce Shop]
// +----------------------------------------------------------------------
// | Copyright (c) vmcshop.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.vmcshop.com/licensed)
// +----------------------------------------------------------------------
// | Author: Shanghai ChenShang Software Technology Co., Ltd.
// +----------------------------------------------------------------------


$goods = array(
    'goods_id',
    'name',
    'store_id',
    'image_id',
    'price',
    'product_id',
);
/**
 *  外来数据配置
 */
 $setting = array(
     'city' => array(
         array(
             'name' => '北京',
             'default' => '1',//默认城市
             'id' => '1',
         ),
         array(
             'name' => '上海',
             'id' => '2',
         ),
         array(
             'name' => '广东',
             'id' => '3',
         )
     ),
     'webnav' => array(
         array(
             'name' => '新品惠',
             'url' => '',
         ),
         array(
             'name' => '大促会',
             'url' => '',
         )
     ),
     'slider' => array(
         array(
             'url' => array(
                  'app' => 'site',
                  'ctl' => 'index',
                  'act' => 'index',
               ),
             'image_id' => 'fafaf366eaefd8a22e69851ebc30a02dc8b3cd52',
         ),
         array(
             'url' => array(
                  'app' => 'site',
                  'ctl' => 'index',
                  'act' => 'index',
               ),
             'image_id' => '4f7b766e1cc62bd67b2adf8edce90df791f76c46',
         ),
         array(
             'url' => array(
                  'app' => 'site',
                  'ctl' => 'index',
                  'act' => 'index',
               ),
             'image_id' => '5a102e5e42ccda868671320889fe1873a231b187',
         ),
     ),

    'floor' => array(
        array(
            'type' => 'china_food',
            'name' => '中餐食材',
            'item' => array(
                array(
                    'default' => '1',
                    'url' => array(
                        'app' => 'b2c',
                        'ctl' => 'site_product',
                        'act' => 'index',
                        'args' => array(
                            '1', '5',//product_id  store_id
                        ),
                    ),
                    'image_id' => 'f7c5a5b54e1ce5cd0fc0c61deaa8eb91',
                    'price' => '9.00',
                    'name' => '鸡爪',
                ),
                array(
                    'url' => array(
                        'app' => 'b2c',
                        'ctl' => 'site_product',
                        'act' => 'index',
                        'args' => array(
                            '4', '5',//product_id  store_id
                        ),
                    ),
                    'image_id' => '1ed82a9cfc269873c808f2b337fd8bfe',
                    'price' => '22.00',
                    'name' => '鸡大腿',
                ),
                array(
                    'url' => array(
                        'app' => 'b2c',
                        'ctl' => 'site_product',
                        'act' => 'index',
                        'args' => array(
                            '7', '5',//product_id  store_id
                        ),
                    ),
                    'image_id' => 'd086b765bb50d049d845e5de4267a8b9',
                    'price' => '22.00',
                    'name' => '鸡大胸',
                ),
                array(
                    'url' => array(
                        'app' => 'b2c',
                        'ctl' => 'site_product',
                        'act' => 'index',
                        'args' => array(
                            '10', '5',//product_id  store_id
                        ),
                    ),
                    'image_id' => 'e08e630a0aa3db2d1367d1576315d7f9',
                    'price' => '18.00',
                    'name' => '鸡翅',
                ),
                array(
                    'url' => array(
                        'app' => 'b2c',
                        'ctl' => 'site_product',
                        'act' => 'index',
                        'args' => array(
                            '13', '5',//product_id  store_id
                        ),
                    ),
                    'image_id' => '766c25ae515fa9fa4b939c3f27bdcd56',
                    'price' => '22.00',
                    'name' => '鸡心',
                ),
                array(
                    'url' => array(
                        'app' => 'b2c',
                        'ctl' => 'site_product',
                        'act' => 'index',
                        'args' => array(
                            '16', '5',//product_id  store_id
                        ),
                    ),
                    'image_id' => '2a33b9c510f7a641a25ea1b45e9cbb63',
                    'price' => '31.00',
                    'name' => '鸡杂',
                ),
                array(
                    'url' => array(
                        'app' => 'b2c',
                        'ctl' => 'site_product',
                        'act' => 'index',
                        'args' => array(
                            '2', '5',//product_id  store_id
                        ),
                    ),
                    'image_id' => '6c6a87a3e0b0af6d8bdbfda714f4ba39',
                    'price' => '17.00',
                    'name' => '鸡爪',
                ),
                array(
                    'url' => array(
                        'app' => 'b2c',
                        'ctl' => 'site_product',
                        'act' => 'index',
                        'args' => array(
                            '17', '5',//product_id  store_id
                        ),
                    ),
                    'image_id' => '2a33b9c510f7a641a25ea1b45e9cbb63',
                    'price' => '63.00',
                    'name' => '鸡杂',
                ),
                array(
                    'url' => array(
                        'app' => 'b2c',
                        'ctl' => 'site_product',
                        'act' => 'index',
                        'args' => array(
                            '11', '5',//product_id  store_id
                        ),
                    ),
                    'image_id' => 'e08e630a0aa3db2d1367d1576315d7f9',
                    'price' => '34.00',
                    'name' => '鸡翅',
                ),
            ),
        ),
    ),
    'store' => array(
        array(
            'name' => '店铺1',
            'url' => array(
                'app' => 'store',
                'ctl' => 'site_store',
                'act' => 'index',
                'args' => array(
                    '1',//storeid
                ),
            ),
            'image_id' =>'dd2505cf2a03611259ad95d00a09cfd4',
        ),
        array(
            'name' => '店铺2',
            'url' => array(
                'app' => 'store',
                'ctl' => 'site_store',
                'act' => 'index',
                'args' => array(
                    '2',//storeid
                ),
            ),
            'image_id' =>'dd2505cf2a03611259ad95d00a09cfd4',
        ),
        array(
            'name' => '店铺3',
            'url' => array(
                'app' => 'store',
                'ctl' => 'site_store',
                'act' => 'index',
                'args' => array(
                    '3',//storeid
                ),
            ),
            'image_id' =>'dd2505cf2a03611259ad95d00a09cfd4',
        ),
        array(
            'name' => '店铺4',
            'url' => array(
                'app' => 'store',
                'ctl' => 'site_store',
                'act' => 'index',
                'args' => array(
                    '4',//storeid
                ),
            ),
            'image_id' =>'dd2505cf2a03611259ad95d00a09cfd4',
        ),
        array(
            'name' => '店铺5',
            'url' => array(
                'app' => 'store',
                'ctl' => 'site_store',
                'act' => 'index',
                'args' => array(
                    '5',//storeid
                ),
            ),
            'image_id' =>'dd2505cf2a03611259ad95d00a09cfd4',
        ),
        array(
            'name' => '店铺6',
            'url' => array(
                'app' => 'store',
                'ctl' => 'site_store',
                'act' => 'index',
                'args' => array(
                    '6',//storeid
                ),
            ),
            'image_id' =>'dd2505cf2a03611259ad95d00a09cfd4',
        ),
        array(
            'name' => '店铺7',
            'url' => array(
                'app' => 'store',
                'ctl' => 'site_store',
                'act' => 'index',
                'args' => array(
                    '7',//storeid
                ),
            ),
            'image_id' =>'dd2505cf2a03611259ad95d00a09cfd4',
        ),
        array(
            'name' => '店铺8',
            'url' => array(
                'app' => 'store',
                'ctl' => 'site_store',
                'act' => 'index',
                'args' => array(
                    '8',//storeid
                ),
            ),
            'image_id' =>'dd2505cf2a03611259ad95d00a09cfd4',
        ),
    ),
    'filter' => array(
        'brand' => array(
            'type' => 'brand_id',
            'item' => array(
                array(
                    'name' => '神龙客',
                    'id' => '1',
                ),
                array(
                    'name' => '多鲜乐',
                    'id' => '2',
                ),
                array(
                    'name' => '美侍客',
                    'id' => '3',
                ),
            ),
        ),
        'price' => array(
            'type' => 'price_id',
            'item' => array(
                array(
                    'name' => '0-40',
                    'id' => '1',
                ),
                array(
                    'name' => '41-100',
                    'id' => '2',
                ),
                array(
                    'name' => '100-200',
                    'id' => '3',
                ),
                array(
                    'name' => '200-400',
                    'id' => '4',
                ),
                array(
                    'name' => '400以上',
                    'id' => '5',
                ),
            ),
        ),
        'origin' => array(
            'type' => 'origin_id',
            'item' => array(
                array(
                    'name' => '上海',
                    'id' => '1',
                ),
                array(
                    'name' => '河南',
                    'id' => '2',
                ),
                array(
                    'name' => '广东',
                    'id' => '3',
                ),
                array(
                    'name' => '天津',
                    'id' => '4',
                ),
                array(
                    'name' => '湖北',
                    'id' => '5',
                ),
            ),
        ),
        'weight' => array(
            'type' => 'weight_id',
            'item' => array(
                array(
                    'name' => '0-5KG',
                    'id' => '1',
                ),
                array(
                    'name' => '5-10KG',
                    'id' => '2',
                ),
                array(
                    'name' => '10-20KG',
                    'id' => '3',
                ),
                array(
                    'name' => '20KG以上',
                    'id' => '4',
                ),
            ),
        ),
    ),
    'cat' => array(
        //一级分类
        array(
            'name' => '鸡肉类',
            'id' => '1',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),
        array(
            'name' => '鸭肉类',
            'id' => '2',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),
        array(
            'name' => '猪肉类',
            'id' => '3',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),
        array(
            'name' => '牛羊肉类',
            'id' => '4',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),

        array(
            'name' => '海产品类',
            'id' => '10',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),
        array(
            'name' => '丸肠水发品',
            'id' => '11',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),
        array(
            'name' => '腌腊制品',
            'id' => '12',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),
        array(
            'name' => '冰品',
            'id' => '13',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),
        array(
            'name' => '速冻点心',
            'id' => '14',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),
        array(
            'name' => '速冻蔬菜',
            'id' => '15',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),
        array(
            'name' => '粮油产品',
            'id' => '16',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),
        array(
            'name' => '调味品',
            'id' => '17',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),
        array(
            'name' => '干货产品',
            'id' => '18',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),
        array(
            'name' => '小菜产品',
            'id' => '19',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),
        array(
            'name' => '儿童产品',
            'id' => '20',
            'cat_lv' => '1',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '0',
        ),
        //end 一级分类
        //
        //二级分类
        array(
            'name' => '鸡大腿',
            'id' => '5',
            'cat_lv' => '2',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '1',
        ),
        array(
            'name' => '鸡大胸',
            'id' => '6',
            'cat_lv' => '2',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '1',
        ),
        array(
            'name' => '鸡爪',
            'id' => '7',
            'cat_lv' => '2',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '1',
        ),
        array(
            'name' => '鸡翅',
            'id' => '8',
            'cat_lv' => '2',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '1',
        ),
        array(
            'name' => '鸡心',
            'id' => '9',
            'cat_lv' => '2',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '1',
        ),
        array(
            'name' => '鸡杂',
            'id' => '21',
            'cat_lv' => '2',
            'order' => '0',
            'has_children' => true,
            'parent_id' => '1',
        ),
        //end二级分类
        // //三级分类
        // array(
        //     'name' => '鸡肉1',
        //     'id' => '7',
        //     'cat_lv' => '3',
        //     'order' => '0',
        //     'has_children' => true,
        //     'parent_id' => '5',
        // ),
        // array(
        //     'name' => '鸡肉2',
        //     'id' => '8',
        //     'cat_lv' => '3',
        //     'order' => '0',
        //     'has_children' => true,
        //     'parent_id' => '5',
        // ),
        // array(
        //     'name' => '鸡腿1',
        //     'id' => '9',
        //     'cat_lv' => '3',
        //     'order' => '0',
        //     'has_children' => true,
        //     'parent_id' => '6',
        // ),
        // array(
        //     'name' => '鸡腿2',
        //     'id' => '10',
        //     'cat_lv' => '3',
        //     'order' => '0',
        //     'has_children' => true,
        //     'parent_id' => '6',
        // ),
        // //end 三级分类
    ),

 );

 $goods_list = array(
                array(
                     'goods_id' => '8',
                     'gid' => 'v16979961',
                     'origin_id' => '1',
                     'weight_id' => '1',
                     'name' => '鸡爪',
                     'type_id' => '0',
                     'cat_id' => '0',
                     'extended_cat' => '',
                     'brand_id' => '7',
                     'marketable' => 'true',
                     'uptime' => '1433233211',
                     'downtime' => '',
                     'last_modify' => '1447324103',
                     'w_order' => '0',
                     'score' => '',
                     'brief' => '',
                     'goods_type' => 'normal',
                     'image_default_id' => 'f7c5a5b54e1ce5cd0fc0c61deaa8eb91',
                     'intro' => '<p><br></p>',
                     'min_buy' => '',
                     'nostore_sell' => '0',
                     'goods_setting' => '',
                     'spec_desc' => 'Array',
                     'disabled' => 'false',
                     'comment_count' => '0',
                     'view_w_count' => '0',
                     'view_count' => '0',
                     'buy_count' => '0',
                     'buy_w_count' => '0',
                     'seller_id' => '0',
                     'checkin' => '1',
                     'params' => '',
                ),
                array(
                     'goods_id' => '7',
                     'gid' => 'v85539078',
                     'origin_id' => '1',
                     'weight_id' => '1',
                     'name' => '鸡大腿',
                     'type_id' => '0',
                     'cat_id' => '19',
                     'extended_cat' => '',
                     'brand_id' => '2',
                     'marketable' => 'true',
                     'uptime' => '1433232741',
                     'downtime' => '',
                     'last_modify' => '1433232741',
                     'w_order' => '0',
                     'score' => '',
                     'brief' => '',
                     'goods_type' => 'normal',
                     'image_default_id' => 'ca1126b7fbd10397b8d0a56778f9efe2',
                     'intro' => '<p><br></p>',
                     'min_buy' => '',
                     'nostore_sell' => '1',
                     'goods_setting' => '',
                     'spec_desc' => '',
                     'disabled' => 'false',
                     'comment_count' => '0',
                     'view_w_count' => '0',
                     'view_count' => '0',
                     'buy_count' => '0',
                     'buy_w_count' => '0',
                     'seller_id' => '0',
                     'checkin' => '1',
                     'params' => '',
                ),
                array(
                     'goods_id' => '6',
                     'gid' => 'v66386676',
                     'origin_id' => '1',
                     'weight_id' => '1',
                     'name' => '鸡大胸',
                     'type_id' => '0',
                     'cat_id' => '18',
                     'extended_cat' => '',
                     'brand_id' => '1',
                     'marketable' => 'true',
                     'uptime' => '1433232552',
                     'downtime' => '',
                     'last_modify' => '1433232552',
                     'w_order' => '0',
                     'score' => '',
                     'brief' => '',
                     'goods_type' => 'normal',
                     'image_default_id' => '0446f3d1afe774ee124e9bff8f7d11a5',
                     'intro' => '',
                     'min_buy' => '',
                     'nostore_sell' => '0',
                     'goods_setting' => '',
                     'spec_desc' => 'Array',
                     'disabled' => 'false',
                     'comment_count' => '0',
                     'view_w_count' => '0',
                     'view_count' => '0',
                     'buy_count' => '0',
                     'buy_w_count' => '0',
                     'seller_id' => '0',
                     'checkin' => '1',
                     'params' => '',
                ),
                array(
                     'goods_id' => '5',
                     'gid' => 'v26635722',
                     'origin_id' => '1',
                     'weight_id' => '1',
                     'name' => '鸡翅',
                     'type_id' => '0',
                     'cat_id' => '13',
                     'extended_cat' => '',
                     'brand_id' => '4',
                     'marketable' => 'true',
                     'uptime' => '1433232215',
                     'downtime' => '',
                     'last_modify' => '1433232215',
                     'w_order' => '0',
                     'score' => '',
                     'brief' => '',
                     'goods_type' => 'normal',
                     'image_default_id' => '8bc55095f398d263cc6acade39fb220a',
                     'intro' => '<p><br></p>',
                     'min_buy' => '',
                     'nostore_sell' => '1',
                     'goods_setting' => '',
                     'spec_desc' => '',
                     'disabled' => 'false',
                     'comment_count' => '0',
                     'view_w_count' => '0',
                     'view_count' => '0',
                     'buy_count' => '0',
                     'buy_w_count' => '0',
                     'seller_id' => '0',
                     'checkin' => '1',
                     'params' => '',
                ),
                array(
                     'goods_id' => '4',
                     'gid' => 'v96359109',
                     'origin_id' => '1',
                     'weight_id' => '1',
                     'name' => '鸡心',
                     'type_id' => '0',
                     'cat_id' => '10',
                     'extended_cat' => '',
                     'brand_id' => '6',
                     'marketable' => 'true',
                     'uptime' => '1433232219',
                     'downtime' => '',
                     'last_modify' => '1433232219',
                     'w_order' => '0',
                     'score' => '',
                     'brief' => '',
                     'goods_type' => 'normal',
                     'image_default_id' => 'c9e0f03807b544b554b6880cda751e00',
                     'intro' => '<p><br></p>',
                     'min_buy' => '',
                     'nostore_sell' => '0',
                     'goods_setting' => '',
                     'spec_desc' => 'Array',
                     'disabled' => 'false',
                     'comment_count' => '0',
                     'view_w_count' => '0',
                     'view_count' => '0',
                     'buy_count' => '0',
                     'buy_w_count' => '0',
                     'seller_id' => '1',
                     'checkin' => '1',
                     'params' => '',
                ),
                array(
                     'goods_id' => '3',
                     'gid' => 'v96635819',
                     'origin_id' => '1',
                     'weight_id' => '1',
                     'name' => '鸡杂',
                     'type_id' => '0',
                     'cat_id' => '10',
                     'extended_cat' => '',
                     'brand_id' => '6',
                     'marketable' => 'true',
                     'uptime' => '1433232223',
                     'downtime' => '',
                     'last_modify' => '1433232223',
                     'w_order' => '0',
                     'score' => '',
                     'brief' => '',
                     'goods_type' => 'normal',
                     'image_default_id' => '611aaf5d05e41a4e43df0212d3671046',
                     'intro' => '<p><br></p>',
                     'min_buy' => '',
                     'nostore_sell' => '0',
                     'goods_setting' => '',
                     'spec_desc' => 'Array',
                     'disabled' => 'false',
                     'comment_count' => '0',
                     'view_w_count' => '0',
                     'view_count' => '0',
                     'buy_count' => '0',
                     'buy_w_count' => '0',
                     'seller_id' => '1',
                     'checkin' => '1',
                     'params' => '',
                ),
                array(
                     'goods_id' => '2',
                     'gid' => 'v95663679',
                     'origin_id' => '1',
                     'weight_id' => '1',
                     'name' => 'FILA斐乐正品2015秋季新款男鞋运动鞋透气复古文化跑鞋',
                     'type_id' => '0',
                     'cat_id' => '10',
                     'extended_cat' => '',
                     'brand_id' => '5',
                     'marketable' => 'true',
                     'uptime' => '1433232228',
                     'downtime' => '',
                     'last_modify' => '1433232228',
                     'w_order' => '0',
                     'score' => '',
                     'brief' => '男款透气跑鞋 简单轻快 凸显穿着品味',
                     'goods_type' => 'normal',
                     'image_default_id' => 'ccf9923ad28aa1dd608e9d4df3bcd045',
                     'intro' => '<p><br></p>',
                     'min_buy' => '',
                     'nostore_sell' => '0',
                     'goods_setting' => '',
                     'spec_desc' => 'Array',
                     'disabled' => 'false',
                     'comment_count' => '0',
                     'view_w_count' => '0',
                     'view_count' => '0',
                     'buy_count' => '0',
                     'buy_w_count' => '0',
                     'seller_id' => '1',
                     'checkin' => '1',
                     'params' => '',
                ),
                array(
                     'goods_id' => '1',
                     'gid' => 'v45663684',
                     'origin_id' => '1',
                     'weight_id' => '1',
                     'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
                     'type_id' => '0',
                     'cat_id' => '6',
                     'extended_cat' => '',
                     'brand_id' => '1',
                     'marketable' => 'true',
                     'uptime' => '1433232235',
                     'downtime' => '',
                     'last_modify' => '1433232235',
                     'w_order' => '0',
                     'score' => '',
                     'brief' => '这款无需合约的 iPhone 6 支持中国移动、中国电信和中国联通的 4G LTE 网络。',
                     'goods_type' => 'normal',
                     'image_default_id' => '69443bbc9329413cddc5080ef5d5bb59',
                     'intro' => '<p><br></p>',
                     'min_buy' => '',
                     'nostore_sell' => '0',
                     'goods_setting' => '',
                     'spec_desc' => 'Array',
                     'disabled' => 'false',
                     'comment_count' => '0',
                     'view_w_count' => '0',
                     'view_count' => '0',
                     'buy_count' => '0',
                     'buy_w_count' => '0',
                     'seller_id' => '1',
                     'checkin' => '1',
                     'params' => '',
                ),
            );


$products = array(
array(
'product_id' => '1',
'goods_id' => '1',
'barcode' => 'iP6-1',
'bn' => 'iP6-0',
'price' => '4988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '4.7英寸显示屏/银色/16GB',
'spec_desc' => '4.7英寸显示屏:::银色:::16GB',
'is_default' => 'true',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '2',
'goods_id' => '1',
'barcode' => 'iP6-7',
'bn' => 'iP6-6',
'price' => '4988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '4.7英寸显示屏/银色/32GB',
'spec_desc' => '4.7英寸显示屏:::银色:::32GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '3',
'goods_id' => '1',
'barcode' => 'iP6-13',
'bn' => 'iP6-12',
'price' => '4988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '4.7英寸显示屏/银色/64GB',
'spec_desc' => '4.7英寸显示屏:::银色:::64GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '4',
'goods_id' => '1',
'barcode' => 'iP6-19',
'bn' => 'iP6-18',
'price' => '4988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '4.7英寸显示屏/银色/128GB',
'spec_desc' => '4.7英寸显示屏:::银色:::128GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '5',
'goods_id' => '1',
'barcode' => 'iP6-25',
'bn' => 'iP6-24',
'price' => '4988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '4.7英寸显示屏/金色/16GB',
'spec_desc' => '4.7英寸显示屏:::金色:::16GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '6',
'goods_id' => '1',
'barcode' => 'iP6-31',
'bn' => 'iP6-30',
'price' => '4988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '4.7英寸显示屏/金色/32GB',
'spec_desc' => '4.7英寸显示屏:::金色:::32GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '7',
'goods_id' => '1',
'barcode' => 'iP6-37',
'bn' => 'iP6-36',
'price' => '4988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '4.7英寸显示屏/金色/64GB',
'spec_desc' => '4.7英寸显示屏:::金色:::64GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '8',
'goods_id' => '1',
'barcode' => 'iP6-43',
'bn' => 'iP6-42',
'price' => '4988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '4.7英寸显示屏/金色/128GB',
'spec_desc' => '4.7英寸显示屏:::金色:::128GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '9',
'goods_id' => '1',
'barcode' => 'iP6-49',
'bn' => 'iP6-48',
'price' => '4988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '4.7英寸显示屏/深灰/16GB',
'spec_desc' => '4.7英寸显示屏:::深灰:::16GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '10',
'goods_id' => '1',
'barcode' => 'iP6-55',
'bn' => 'iP6-54',
'price' => '4988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '4.7英寸显示屏/深灰/32GB',
'spec_desc' => '4.7英寸显示屏:::深灰:::32GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '11',
'goods_id' => '1',
'barcode' => 'iP6-61',
'bn' => 'iP6-60',
'price' => '4988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '4.7英寸显示屏/深灰/64GB',
'spec_desc' => '4.7英寸显示屏:::深灰:::64GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '12',
'goods_id' => '1',
'barcode' => 'iP6-67',
'bn' => 'iP6-66',
'price' => '4988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '4.7英寸显示屏/深灰/128GB',
'spec_desc' => '4.7英寸显示屏:::深灰:::128GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '13',
'goods_id' => '1',
'barcode' => 'iP6-73',
'bn' => 'iP6-72',
'price' => '6988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '5.5英寸显示屏/银色/16GB',
'spec_desc' => '5.5英寸显示屏:::银色:::16GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '14',
'goods_id' => '1',
'barcode' => 'iP6-79',
'bn' => 'iP6-78',
'price' => '6988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '5.5英寸显示屏/银色/32GB',
'spec_desc' => '5.5英寸显示屏:::银色:::32GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '15',
'goods_id' => '1',
'barcode' => 'iP6-85',
'bn' => 'iP6-84',
'price' => '6988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '5.5英寸显示屏/银色/64GB',
'spec_desc' => '5.5英寸显示屏:::银色:::64GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '16',
'goods_id' => '1',
'barcode' => 'iP6-91',
'bn' => 'iP6-90',
'price' => '6988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '5.5英寸显示屏/银色/128GB',
'spec_desc' => '5.5英寸显示屏:::银色:::128GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '17',
'goods_id' => '1',
'barcode' => 'iP6-97',
'bn' => 'iP6-96',
'price' => '6988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '5.5英寸显示屏/金色/16GB',
'spec_desc' => '5.5英寸显示屏:::金色:::16GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '18',
'goods_id' => '1',
'barcode' => 'iP6-103',
'bn' => 'iP6-102',
'price' => '6988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '5.5英寸显示屏/金色/32GB',
'spec_desc' => '5.5英寸显示屏:::金色:::32GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '19',
'goods_id' => '1',
'barcode' => 'iP6-109',
'bn' => 'iP6-108',
'price' => '6988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '5.5英寸显示屏/金色/64GB',
'spec_desc' => '5.5英寸显示屏:::金色:::64GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '20',
'goods_id' => '1',
'barcode' => 'iP6-115',
'bn' => 'iP6-114',
'price' => '6988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '5.5英寸显示屏/金色/128GB',
'spec_desc' => '5.5英寸显示屏:::金色:::128GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '21',
'goods_id' => '1',
'barcode' => 'iP6-121',
'bn' => 'iP6-120',
'price' => '6988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '5.5英寸显示屏/深灰/16GB',
'spec_desc' => '5.5英寸显示屏:::深灰:::16GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '22',
'goods_id' => '1',
'barcode' => 'iP6-127',
'bn' => 'iP6-126',
'price' => '6988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '5.5英寸显示屏/深灰/32GB',
'spec_desc' => '5.5英寸显示屏:::深灰:::32GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '23',
'goods_id' => '1',
'barcode' => 'iP6-133',
'bn' => 'iP6-132',
'price' => '6988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '5.5英寸显示屏/深灰/64GB',
'spec_desc' => '5.5英寸显示屏:::深灰:::64GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '24',
'goods_id' => '1',
'barcode' => 'iP6-139',
'bn' => 'iP6-138',
'price' => '6988.000',
'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
'weight' => '200.000',
'unit' => '部',
'spec_info' => '5.5英寸显示屏/深灰/128GB',
'spec_desc' => '5.5英寸显示屏:::深灰:::128GB',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232235',
'downtime' => '',
'last_modify' => '1433232235',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '25',
'goods_id' => '2',
'barcode' => '492015-1',
'bn' => '1fila2015-0',
'price' => '680.000',
'name' => 'FILA斐乐正品2015秋季新款男鞋运动鞋透气复古文化跑鞋',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '41/深蓝',
'spec_desc' => '41:::深蓝',
'is_default' => 'true',
'image_id' => '',
'uptime' => '1433232228',
'downtime' => '',
'last_modify' => '1433232228',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '26',
'goods_id' => '2',
'barcode' => '492015-7',
'bn' => '1fila2015-6',
'price' => '680.000',
'name' => 'FILA斐乐正品2015秋季新款男鞋运动鞋透气复古文化跑鞋',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '41/雪山白',
'spec_desc' => '41:::雪山白',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232228',
'downtime' => '',
'last_modify' => '1433232228',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '27',
'goods_id' => '2',
'barcode' => '492015-13',
'bn' => '1fila2015-12',
'price' => '680.000',
'name' => 'FILA斐乐正品2015秋季新款男鞋运动鞋透气复古文化跑鞋',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '42/深蓝',
'spec_desc' => '42:::深蓝',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232228',
'downtime' => '',
'last_modify' => '1433232228',

'disabled' => 'false',
'marketable' => 'true',
),
array(
'product_id' => '28',
'goods_id' => '2',
'barcode' => '492015-19',
'bn' => '1fila2015-18',
'price' => '680.000',
'name' => 'FILA斐乐正品2015秋季新款男鞋运动鞋透气复古文化跑鞋',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '42/雪山白',
'spec_desc' => '42:::雪山白',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232228',
'downtime' => '',
'last_modify' => '1433232228',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '29',
'goods_id' => '2',
'barcode' => '492015-25',
'bn' => '1fila2015-24',
'price' => '680.000',
'name' => 'FILA斐乐正品2015秋季新款男鞋运动鞋透气复古文化跑鞋',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '43/深蓝',
'spec_desc' => '43:::深蓝',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232228',
'downtime' => '',
'last_modify' => '1433232228',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '30',
'goods_id' => '2',
'barcode' => '492015-31',
'bn' => '1fila2015-30',
'price' => '680.000',
'name' => 'FILA斐乐正品2015秋季新款男鞋运动鞋透气复古文化跑鞋',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '43/雪山白',
'spec_desc' => '43:::雪山白',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232228',
'downtime' => '',
'last_modify' => '1433232228',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '31',
'goods_id' => '3',
'barcode' => 'nb2015-1',
'bn' => 'nb2015-0',
'price' => '699.000',
'name' => 'New Balance/NB 男鞋女鞋 复古鞋 跑步运动休闲鞋',
'weight' => '0.000',
'unit' => '双',
'spec_info' => '37/夏威夷风情',
'spec_desc' => '37:::夏威夷风情',
'is_default' => 'true',
'image_id' => '',
'uptime' => '1433232223',
'downtime' => '',
'last_modify' => '1433232223',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '32',
'goods_id' => '3',
'barcode' => 'nb2015-7',
'bn' => 'nb2015-6',
'price' => '699.000',
'name' => 'New Balance/NB 男鞋女鞋 复古鞋 跑步运动休闲鞋',
'weight' => '0.000',
'unit' => '双',
'spec_info' => '38/夏威夷风情',
'spec_desc' => '38:::夏威夷风情',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232223',
'downtime' => '',
'last_modify' => '1433232223',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '33',
'goods_id' => '3',
'barcode' => 'nb2015-13',
'bn' => 'nb2015-12',
'price' => '699.000',
'name' => 'New Balance/NB 男鞋女鞋 复古鞋 跑步运动休闲鞋',
'weight' => '0.000',
'unit' => '双',
'spec_info' => '39/夏威夷风情',
'spec_desc' => '39:::夏威夷风情',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232223',
'downtime' => '',
'last_modify' => '1433232223',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '34',
'goods_id' => '3',
'barcode' => 'nb2015-19',
'bn' => 'nb2015-18',
'price' => '699.000',
'name' => 'New Balance/NB 男鞋女鞋 复古鞋 跑步运动休闲鞋',
'weight' => '0.000',
'unit' => '双',
'spec_info' => '41/夏威夷风情',
'spec_desc' => '41:::夏威夷风情',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232223',
'downtime' => '',
'last_modify' => '1433232223',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '35',
'goods_id' => '3',
'barcode' => 'nb2015-25',
'bn' => 'nb2015-24',
'price' => '699.000',
'name' => 'New Balance/NB 男鞋女鞋 复古鞋 跑步运动休闲鞋',
'weight' => '0.000',
'unit' => '双',
'spec_info' => '42/夏威夷风情',
'spec_desc' => '42:::夏威夷风情',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232223',
'downtime' => '',
'last_modify' => '1433232223',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '36',
'goods_id' => '3',
'barcode' => 'nb2015-31',
'bn' => 'nb2015-30',
'price' => '699.000',
'name' => 'New Balance/NB 男鞋女鞋 复古鞋 跑步运动休闲鞋',
'weight' => '0.000',
'unit' => '双',
'spec_info' => '43/夏威夷风情',
'spec_desc' => '43:::夏威夷风情',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232223',
'downtime' => '',
'last_modify' => '1433232223',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '37',
'goods_id' => '4',
'barcode' => 'nb12015-1',
'bn' => 'nb12015-0',
'price' => '419.300',
'name' => 'New Balance/NB 男鞋 经典复古鞋 跑步鞋 休闲鞋',
'weight' => '0.000',
'unit' => '双',
'spec_info' => '42/亮蓝',
'spec_desc' => '42:::亮蓝',
'is_default' => 'true',
'image_id' => '',
'uptime' => '1433232219',
'downtime' => '',
'last_modify' => '1433232219',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '38',
'goods_id' => '4',
'barcode' => 'nb12015-7',
'bn' => 'nb12015-6',
'price' => '419.300',
'name' => 'New Balance/NB 男鞋 经典复古鞋 跑步鞋 休闲鞋',
'weight' => '0.000',
'unit' => '双',
'spec_info' => '42/尊贵棕',
'spec_desc' => '42:::尊贵棕',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232219',
'downtime' => '',
'last_modify' => '1433232219',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '39',
'goods_id' => '4',
'barcode' => 'nb12015-13',
'bn' => 'nb12015-12',
'price' => '419.300',
'name' => 'New Balance/NB 男鞋 经典复古鞋 跑步鞋 休闲鞋',
'weight' => '0.000',
'unit' => '双',
'spec_info' => '43/亮蓝',
'spec_desc' => '43:::亮蓝',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232219',
'downtime' => '',
'last_modify' => '1433232219',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '40',
'goods_id' => '4',
'barcode' => 'nb12015-19',
'bn' => 'nb12015-18',
'price' => '419.300',
'name' => 'New Balance/NB 男鞋 经典复古鞋 跑步鞋 休闲鞋',
'weight' => '0.000',
'unit' => '双',
'spec_info' => '43/尊贵棕',
'spec_desc' => '43:::尊贵棕',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232219',
'downtime' => '',
'last_modify' => '1433232219',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '41',
'goods_id' => '4',
'barcode' => 'nb12015-25',
'bn' => 'nb12015-24',
'price' => '419.300',
'name' => 'New Balance/NB 男鞋 经典复古鞋 跑步鞋 休闲鞋',
'weight' => '0.000',
'unit' => '双',
'spec_info' => '44/亮蓝',
'spec_desc' => '44:::亮蓝',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232219',
'downtime' => '',
'last_modify' => '1433232219',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '42',
'goods_id' => '4',
'barcode' => 'nb12015-31',
'bn' => 'nb12015-30',
'price' => '419.300',
'name' => 'New Balance/NB 男鞋 经典复古鞋 跑步鞋 休闲鞋',
'weight' => '0.000',
'unit' => '双',
'spec_info' => '44/尊贵棕',
'spec_desc' => '44:::尊贵棕',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232219',
'downtime' => '',
'last_modify' => '1433232219',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '43',
'goods_id' => '4',
'barcode' => 'nb12015-37',
'bn' => 'nb12015-36',
'price' => '419.300',
'name' => 'New Balance/NB 男鞋 经典复古鞋 跑步鞋 休闲鞋',
'weight' => '0.000',
'unit' => '双',
'spec_info' => '45/亮蓝',
'spec_desc' => '45:::亮蓝',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232219',
'downtime' => '',
'last_modify' => '1433232219',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '44',
'goods_id' => '4',
'barcode' => 'nb12015-43',
'bn' => 'nb12015-42',
'price' => '419.300',
'name' => 'New Balance/NB 男鞋 经典复古鞋 跑步鞋 休闲鞋',
'weight' => '0.000',
'unit' => '双',
'spec_info' => '45/尊贵棕',
'spec_desc' => '45:::尊贵棕',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232219',
'downtime' => '',
'last_modify' => '1433232219',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '45',
'goods_id' => '5',
'barcode' => 'fx2015',
'bn' => 'fx2015',
'price' => '5.000',
'name' => '费雪婴儿游戏桌 多功能双语学习桌早教益智bjv34 儿童节礼物',
'weight' => '200.000',
'unit' => '件',
'spec_info' => '',
'spec_desc' => '',
'is_default' => 'true',
'image_id' => '',
'uptime' => '1433232215',
'downtime' => '',
'last_modify' => '1433232215',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '46',
'goods_id' => '6',
'barcode' => 'ipadmini3-1',
'bn' => 'ipadmini3-0',
'price' => '2999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '土豪金/32G/WIFI',
'spec_desc' => '土豪金:::32G:::WIFI',
'is_default' => 'true',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '99',
'goods_id' => '6',
'barcode' => 'ipadmini3-7',
'bn' => 'ipadmini3-6',
'price' => '2999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '土豪金/32G/WIFI 3G',
'spec_desc' => '土豪金:::32G:::WIFI 3G',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '100',
'goods_id' => '6',
'barcode' => 'ipadmini3-13',
'bn' => 'ipadmini3-12',
'price' => '3999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '土豪金/32G/WIFI 3G 4G全制式',
'spec_desc' => '土豪金:::32G:::WIFI 3G 4G全制式',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '101',
'goods_id' => '6',
'barcode' => 'ipadmini3-19',
'bn' => 'ipadmini3-18',
'price' => '3999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '土豪金/64G/WIFI',
'spec_desc' => '土豪金:::64G:::WIFI',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '102',
'goods_id' => '6',
'barcode' => 'ipadmini3-25',
'bn' => 'ipadmini3-24',
'price' => '3999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '土豪金/64G/WIFI 3G',
'spec_desc' => '土豪金:::64G:::WIFI 3G',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '103',
'goods_id' => '6',
'barcode' => 'ipadmini3-31',
'bn' => 'ipadmini3-30',
'price' => '4999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '土豪金/64G/WIFI 3G 4G全制式',
'spec_desc' => '土豪金:::64G:::WIFI 3G 4G全制式',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '104',
'goods_id' => '6',
'barcode' => 'ipadmini3-37',
'bn' => 'ipadmini3-36',
'price' => '4999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '土豪金/128G/WIFI',
'spec_desc' => '土豪金:::128G:::WIFI',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '105',
'goods_id' => '6',
'barcode' => 'ipadmini3-43',
'bn' => 'ipadmini3-42',
'price' => '4999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '土豪金/128G/WIFI 3G',
'spec_desc' => '土豪金:::128G:::WIFI 3G',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '106',
'goods_id' => '6',
'barcode' => 'ipadmini3-49',
'bn' => 'ipadmini3-48',
'price' => '5999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '土豪金/128G/WIFI 3G 4G全制式',
'spec_desc' => '土豪金:::128G:::WIFI 3G 4G全制式',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '107',
'goods_id' => '6',
'barcode' => 'ipadmini3-55',
'bn' => 'ipadmini3-54',
'price' => '5999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '珍珠白/32G/WIFI',
'spec_desc' => '珍珠白:::32G:::WIFI',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '108',
'goods_id' => '6',
'barcode' => 'ipadmini3-61',
'bn' => 'ipadmini3-60',
'price' => '5999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '珍珠白/32G/WIFI 3G',
'spec_desc' => '珍珠白:::32G:::WIFI 3G',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '109',
'goods_id' => '6',
'barcode' => 'ipadmini3-67',
'bn' => 'ipadmini3-66',
'price' => '6999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '珍珠白/32G/WIFI 3G 4G全制式',
'spec_desc' => '珍珠白:::32G:::WIFI 3G 4G全制式',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '110',
'goods_id' => '6',
'barcode' => 'ipadmini3-73',
'bn' => 'ipadmini3-72',
'price' => '6999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '珍珠白/64G/WIFI',
'spec_desc' => '珍珠白:::64G:::WIFI',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '111',
'goods_id' => '6',
'barcode' => 'ipadmini3-79',
'bn' => 'ipadmini3-78',
'price' => '6999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '珍珠白/64G/WIFI 3G',
'spec_desc' => '珍珠白:::64G:::WIFI 3G',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '112',
'goods_id' => '6',
'barcode' => 'ipadmini3-85',
'bn' => 'ipadmini3-84',
'price' => '7999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '珍珠白/64G/WIFI 3G 4G全制式',
'spec_desc' => '珍珠白:::64G:::WIFI 3G 4G全制式',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '113',
'goods_id' => '6',
'barcode' => 'ipadmini3-91',
'bn' => 'ipadmini3-90',
'price' => '8999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '珍珠白/128G/WIFI',
'spec_desc' => '珍珠白:::128G:::WIFI',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '114',
'goods_id' => '6',
'barcode' => 'ipadmini3-97',
'bn' => 'ipadmini3-96',
'price' => '8999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '珍珠白/128G/WIFI 3G',
'spec_desc' => '珍珠白:::128G:::WIFI 3G',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '115',
'goods_id' => '6',
'barcode' => 'ipadmini3-103',
'bn' => 'ipadmini3-102',
'price' => '28999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '珍珠白/128G/WIFI 3G 4G全制式',
'spec_desc' => '珍珠白:::128G:::WIFI 3G 4G全制式',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '116',
'goods_id' => '6',
'barcode' => 'ipadmini3-109',
'bn' => 'ipadmini3-108',
'price' => '2999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '亚光灰/32G/WIFI',
'spec_desc' => '亚光灰:::32G:::WIFI',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '117',
'goods_id' => '6',
'barcode' => 'ipadmini3-115',
'bn' => 'ipadmini3-114',
'price' => '2999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '亚光灰/32G/WIFI 3G',
'spec_desc' => '亚光灰:::32G:::WIFI 3G',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '118',
'goods_id' => '6',
'barcode' => 'ipadmini3-121',
'bn' => 'ipadmini3-120',
'price' => '2999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '亚光灰/32G/WIFI 3G 4G全制式',
'spec_desc' => '亚光灰:::32G:::WIFI 3G 4G全制式',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '119',
'goods_id' => '6',
'barcode' => 'ipadmini3-127',
'bn' => 'ipadmini3-126',
'price' => '2999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '亚光灰/64G/WIFI',
'spec_desc' => '亚光灰:::64G:::WIFI',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '120',
'goods_id' => '6',
'barcode' => 'ipadmini3-133',
'bn' => 'ipadmini3-132',
'price' => '2999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '亚光灰/64G/WIFI 3G',
'spec_desc' => '亚光灰:::64G:::WIFI 3G',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '121',
'goods_id' => '6',
'barcode' => 'ipadmini3-139',
'bn' => 'ipadmini3-138',
'price' => '2999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '亚光灰/64G/WIFI 3G 4G全制式',
'spec_desc' => '亚光灰:::64G:::WIFI 3G 4G全制式',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '122',
'goods_id' => '6',
'barcode' => 'ipadmini3-145',
'bn' => 'ipadmini3-144',
'price' => '2999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '亚光灰/128G/WIFI',
'spec_desc' => '亚光灰:::128G:::WIFI',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '123',
'goods_id' => '6',
'barcode' => 'ipadmini3-151',
'bn' => 'ipadmini3-150',
'price' => '2999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '亚光灰/128G/WIFI 3G',
'spec_desc' => '亚光灰:::128G:::WIFI 3G',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '124',
'goods_id' => '6',
'barcode' => 'ipadmini3-157',
'bn' => 'ipadmini3-156',
'price' => '2999.000',
'name' => 'iPad Mini 第三代高清平板电脑',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '亚光灰/128G/WIFI 3G 4G全制式',
'spec_desc' => '亚光灰:::128G:::WIFI 3G 4G全制式',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433232552',
'downtime' => '',
'last_modify' => '1433232552',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '125',
'goods_id' => '7',
'barcode' => '2200111',
'bn' => 'xiaomi001',
'price' => '149.000',
'name' => '现货包邮 小米空气净化器滤芯小米智能空气净化器高密度滤网',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '',
'spec_desc' => '',
'is_default' => 'true',
'image_id' => '',
'uptime' => '1433232741',
'downtime' => '',
'last_modify' => '1433232741',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '126',
'goods_id' => '8',
'barcode' => 'gap0991-1',
'bn' => 'gap0991-0',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '31(175/78A)/朱红',
'spec_desc' => '31(175/78A):::朱红',
'is_default' => 'true',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '127',
'goods_id' => '8',
'barcode' => 'gap0991-7',
'bn' => 'gap0991-6',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '31(175/78A)/蔚蓝',
'spec_desc' => '31(175/78A):::蔚蓝',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '128',
'goods_id' => '8',
'barcode' => 'gap0991-13',
'bn' => 'gap0991-12',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '31(175/78A)/浅绿',
'spec_desc' => '31(175/78A):::浅绿',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '129',
'goods_id' => '8',
'barcode' => 'gap0991-19',
'bn' => 'gap0991-18',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '31(175/78A)/自然黄',
'spec_desc' => '31(175/78A):::自然黄',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '130',
'goods_id' => '8',
'barcode' => 'gap0991-25',
'bn' => 'gap0991-24',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '31(175/78A)/黑色',
'spec_desc' => '31(175/78A):::黑色',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '131',
'goods_id' => '8',
'barcode' => 'gap0991-31',
'bn' => 'gap0991-30',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '36(180/90A)/朱红',
'spec_desc' => '36(180/90A):::朱红',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '132',
'goods_id' => '8',
'barcode' => 'gap0991-37',
'bn' => 'gap0991-36',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '36(180/90A)/蔚蓝',
'spec_desc' => '36(180/90A):::蔚蓝',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '133',
'goods_id' => '8',
'barcode' => 'gap0991-43',
'bn' => 'gap0991-42',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '36(180/90A)/浅绿',
'spec_desc' => '36(180/90A):::浅绿',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '134',
'goods_id' => '8',
'barcode' => 'gap0991-49',
'bn' => 'gap0991-48',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '36(180/90A)/自然黄',
'spec_desc' => '36(180/90A):::自然黄',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '135',
'goods_id' => '8',
'barcode' => 'gap0991-55',
'bn' => 'gap0991-54',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '36(180/90A)/黑色',
'spec_desc' => '36(180/90A):::黑色',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '136',
'goods_id' => '8',
'barcode' => 'gap0991-61',
'bn' => 'gap0991-60',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '42(185/110A)/朱红',
'spec_desc' => '42(185/110A):::朱红',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '137',
'goods_id' => '8',
'barcode' => 'gap0991-67',
'bn' => 'gap0991-66',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '42(185/110A)/蔚蓝',
'spec_desc' => '42(185/110A):::蔚蓝',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '138',
'goods_id' => '8',
'barcode' => 'gap0991-73',
'bn' => 'gap0991-72',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '42(185/110A)/浅绿',
'spec_desc' => '42(185/110A):::浅绿',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '139',
'goods_id' => '8',
'barcode' => 'gap0991-79',
'bn' => 'gap0991-78',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '42(185/110A)/自然黄',
'spec_desc' => '42(185/110A):::自然黄',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),array(
'product_id' => '140',
'goods_id' => '8',
'barcode' => 'gap0991-85',
'bn' => 'gap0991-84',
'price' => '239.000',
'name' => 'Gap多选色全棉纯色舒适休闲短裤',
'weight' => '0.000',
'unit' => '件',
'spec_info' => '42(185/110A)/黑色',
'spec_desc' => '42(185/110A):::黑色',
'is_default' => 'false',
'image_id' => '',
'uptime' => '1433233211',
'downtime' => '',
'last_modify' => '1433233211',

'disabled' => 'false',
'marketable' => 'true',
),);


$order_list = array(
array(
'order_id' => '4911465023782',
'createtime' => '1448250410',
'last_modified' => '1448250410',
'status' => 'active',
'confirm' => 'N',
'pay_status' => '0',
'payed' => '0.000',
'is_cod' => 'N',
'need_shipping' => 'Y',
'ship_status' => '0',
'pay_app' => 'offline',
'dlytype_id' => '1',
'member_id' => '13',
'store_id' => '5',
'consignee_name' => '张三',
'consignee_area' => 'mainland:上海/上海市/浦东新区:35',
'consignee_address' => '星光大道',
'consignee_zip' => '100000',
'consignee_tel' => '123456',
'consignee_email' => '',
'consignee_mobile' => '13811112222',
'weight' => '200.000',
'quantity' => '1',
'need_invoice' => 'false',
'invoice_title' => '',
'invoice_addon' => '',
),
array(
'order_id' => '4911462264813',
'createtime' => '1448250382',
'last_modified' => '1448250382',
'status' => 'active',
'confirm' => 'N',
'pay_status' => '0',
'payed' => '0.000',
'is_cod' => 'N',
'need_shipping' => 'Y',
'ship_status' => '0',
'pay_app' => 'offline',
'dlytype_id' => '1',
'member_id' => '13',
'store_id' => '5',
'consignee_name' => '张三',
'consignee_area' => 'mainland:上海/上海市/浦东新区:35',
'consignee_address' => '星光大道',
'consignee_zip' => '100000',
'consignee_tel' => '123456',
'consignee_email' => '',
'consignee_mobile' => '13811112222',
'weight' => '0.000',
'quantity' => '1',
'need_invoice' => 'false',
'invoice_title' => '',
'invoice_addon' => '',
),
array(
'order_id' => '4911375707757',
'createtime' => '1448249877',
'last_modified' => '1448249877',
'status' => 'active',
'confirm' => 'N',
'pay_status' => '0',
'payed' => '0.000',
'is_cod' => 'N',
'need_shipping' => 'Y',
'ship_status' => '0',
'pay_app' => 'offline',
'dlytype_id' => '1',
'member_id' => '13',
'store_id' => '5',
'consignee_name' => '张三',
'consignee_area' => 'mainland:上海/上海市/浦东新区:35',
'consignee_address' => '星光大道',
'consignee_zip' => '100000',
'consignee_tel' => '123456',
'consignee_email' => '',
'consignee_mobile' => '13811112222',
'weight' => '400.000',
'quantity' => '5',
'need_invoice' => 'false',
'invoice_title' => '',
'invoice_addon' => '',
),);
$order_list_items = array(
array(
    'item_id' => '1',
    'order_id' => '3516324142097',
    'product_id' => '126',
    'goods_id' => '8',
    'bn' => 'gap0991-0',
    'name' => 'Gap多选色全棉纯色舒适休闲短裤',
    'spec_info' => '31(175/78A)/朱红',
    'image_id' => '8cb3b3b84e1eba26e7e5748514590ed5',
    'cost' => '',
    'price' => '239.000',
    'member_lv_price' => '239.000',
    'buy_price' => '239.000',
    'amount' => '239.000',
    'score' => '',
    'weight' => '0',
    'nums' => '1',
    'sendnum' => '0',
    'addon' => '',
    'item_type' => 'product',
),
array(
    'item_id' => '2',
    'order_id' => '3516340441729',
    'product_id' => '126',
    'goods_id' => '8',
    'bn' => 'gap0991-0',
    'name' => 'Gap多选色全棉纯色舒适休闲短裤',
    'spec_info' => '31(175/78A)/朱红',
    'image_id' => '8cb3b3b84e1eba26e7e5748514590ed5',
    'cost' => '',
    'price' => '239.000',
    'member_lv_price' => '239.000',
    'buy_price' => '239.000',
    'amount' => '239.000',
    'score' => '',
    'weight' => '0',
    'nums' => '1',
    'sendnum' => '0',
    'addon' => '',
    'item_type' => 'product',
),
array(
    'item_id' => '3',
    'order_id' => '3516451282422',
    'product_id' => '125',
    'goods_id' => '7',
    'bn' => 'xiaomi001',
    'name' => '现货包邮 小米空气净化器滤芯小米智能空气净化器高密度滤网',
    'spec_info' => '',
    'image_id' => '8a7f5ca8819a286a2d314a253e3cc8ab',
    'cost' => '',
    'price' => '149.000',
    'member_lv_price' => '149.000',
    'buy_price' => '149.000',
    'amount' => '149.000',
    'score' => '',
    'weight' => '0',
    'nums' => '1',
    'sendnum' => '0',
    'addon' => '',
    'item_type' => 'product',
),
array(
    'item_id' => '8',
    'order_id' => '4911375707757',
    'product_id' => '46',
    'goods_id' => '6',
    'bn' => 'ipadmini3-0',
    'name' => 'iPad Mini 第三代高清平板电脑',
    'spec_info' => '土豪金/32G/WIFI',
    'image_id' => '8d2a0be90a514ecb51ca01b843142b82',
    'cost' => '',
    'price' => '2999.000',
    'member_lv_price' => '2999.000',
    'buy_price' => '2999.000',
    'amount' => '2999.000',
    'score' => '',
    'weight' => '0',
    'nums' => '1',
    'sendnum' => '0',
    'addon' => '',
    'item_type' => 'product',
),
array(
    'item_id' => '9',
    'order_id' => '4911462264813',
    'product_id' => '37',
    'goods_id' => '4',
    'bn' => 'nb12015-0',
    'name' => 'New Balance/NB 男鞋 经典复古鞋 跑步鞋 休闲鞋',
    'spec_info' => '42/亮蓝',
    'image_id' => 'd63a67731c62829909b55a730f24a55b',
    'cost' => '',
    'price' => '419.300',
    'member_lv_price' => '419.300',
    'buy_price' => '419.300',
    'amount' => '419.300',
    'score' => '',
    'weight' => '0',
    'nums' => '1',
    'sendnum' => '0',
    'addon' => '',
    'item_type' => 'product',
),
array(
    'item_id' => '10',
    'order_id' => '4911465023782',
    'product_id' => '1',
    'goods_id' => '1',
    'bn' => 'iP6-0',
    'name' => 'Apple iPhone 6 美国官方直邮三网合一免合约机',
    'spec_info' => '4.7英寸显示屏/银色/16GB',
    'image_id' => '69443bbc9329413cddc5080ef5d5bb59',
    'cost' => '',
    'price' => '4988.000',
    'member_lv_price' => '4988.000',
    'buy_price' => '4988.000',
    'amount' => '4988.000',
    'score' => '',
    'weight' => '200',
    'nums' => '1',
    'sendnum' => '0',
    'addon' => '',
    'item_type' => 'product',
),);

$store = array(
    array(
        'store_id' => '5',
        'seller_id' => '9',
        'status' => '1',
        'store_name' => '沙县小吃食材专营批发店',
        'logo' => '',
    ),
);
